--EFETUADA A CRIACAO DOS SCRIPTS QUE IRAO FAZER A CARGA DOS DADOS INICIAIS
INSERT INTO ESTUDANTE (NOME, EMAIL, TELEFONE, MATRICULA, CURSO) VALUES('Xawoy','xawoy@tms.com.br', '7777', '123456', 'Engenharia da Computação')
INSERT INTO ESTUDANTE (NOME, EMAIL, TELEFONE, MATRICULA, CURSO) VALUES('Furae','furae@tms.com.br', '7778', '678912', 'Ciência da Computação')
INSERT INTO ESTUDANTE (NOME, EMAIL, TELEFONE, MATRICULA, CURSO) VALUES('Fupuy','fupuy@tms.com.br', '7779', '321654', 'Engenharia da Computação')
INSERT INTO ESTUDANTE (NOME, EMAIL, TELEFONE, MATRICULA, CURSO) VALUES('Xawoy','xawoy@tms.com.br', '7780', '654987', 'Análise de Dados')
INSERT INTO ESTUDANTE (NOME, EMAIL, TELEFONE, MATRICULA, CURSO) VALUES('Xawoy','xawoy@tms.com.br', '7781', '666131', 'Engenharia da Computação')